--호접지몽(슬리핑 버터플라이)
local s,id=GetID()
function s.initial_effect(c)
	local e1=MakeEff(c,"S")
	e1:SetCode(EFFECT_TRAP_ACT_IN_HAND)
	e1:SetProperty(EFFECT_FLAG_CANNOT_DISABLE)
	c:RegisterEffect(e1)
	local e2=MakeEff(c,"S")
	e2:SetCode(EFFECT_TRAP_ACT_IN_SET_TURN)
	e2:SetProperty(EFFECT_FLAG_CANNOT_DISABLE+EFFECT_FLAG_SET_AVAILABLE)
	c:RegisterEffect(e2)
	local e3=MakeEff(c,"A")
	e3:SetCode(EVENT_FREE_CHAIN)
	e3:SetCL(1,id,EFFECT_COUNT_CODE_OATH)
	c:RegisterEffect(e3)
	local e4=MakeEff(c,"F","S")
	e4:SetCode(EFFECT_TRAP_ACT_IN_HAND)
	e4:SetCL(1,0,EFFECT_COUNT_CODE_SINGLE)
	e4:SetTR("H",0)
	e4:SetTarget(s.tar4)
	c:RegisterEffect(e4)
	local e5=MakeEff(c,"F","S")
	e5:SetCode(EFFECT_TRAP_ACT_IN_SET_TURN)
	e5:SetProperty(EFFECT_FLAG_SET_AVAILABLE)
	e5:SetCL(1,0,EFFECT_COUNT_CODE_SINGLE)
	e5:SetTR("S",0)
	e5:SetTarget(s.tar4)
	c:RegisterEffect(e5)
	local e6=MakeEff(c,"F","S")
	e6:SetCode(EFFECT_CANNOT_BE_EFFECT_TARGET)
	e6:SetProperty(EFFECT_FLAG_IGNORE_IMMUNE)
	e6:SetTR("O",0)
	e6:SetCondition(s.con6)
	e6:SetValue(aux.tgoval)
	e6:SetTarget(s.tar6)
	c:RegisterEffect(e6)
	local e7=e6:Clone()
	e7:SetCode(EFFECT_INDESTRUCTABLE_EFFECT)
	e7:SetCondition(s.con7)
	e7:SetValue(aux.indoval)
	c:RegisterEffect(e7)
end
function s.tar4(e,c)
	return c:IsType(TYPE_CONTINUOUS) and not c:IsCode(id)
end
function s.con6(e)
	local tp=e:GetHandlerPlayer()
	return Duel.GetTurnPlayer()==tp
end
function s.tar6(e,c)
	return not c:IsCode(id)
end
function s.con7(e)
	local tp=e:GetHandlerPlayer()
	return Duel.GetTurnPlayer()==tp
end