--왕립 간이도서관
local s,id=GetID()
function s.initial_effect(c)
	local e1=MakeEff(c,"A")
	e1:SetCode(EVENT_FREE_CHAIN)
	e1:SetCategory(CATEGORY_SPECIAL_SUMMON)
	e1:SetCL(1,id,EFFECT_COUNT_CODE_OATH)
	WriteEff(e1,1,"TO")
	c:RegisterEffect(e1)
end
function s.tar1(e,tp,eg,ep,ev,re,r,rp,chk)
	local c=e:GetHandler()
	if chk==0 then
		return true
	end
	if e:IsHasType(EFFECT_TYPE_ACTIVATE) then
		Duel.SOI(0,CATEGORY_SPECIAL_SUMMON,c,1,0,0)
	end
end
function s.op1(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	local e1=MakeEff(c,"FC")
	e1:SetCode(EVENT_CHAIN_SOLVED)
	e1:SetCL(3)
	e1:SetReset(RESET_PHASE+PHASE_END)
	e1:SetCondition(s.ocon11)
	e1:SetOperation(s.oop11)
	Duel.RegisterEffect(e1,tp)
end
function s.ocon11(e,tp,eg,ep,ev,re,r,rp)
	local rc=re:GetHandler()
	return re:IsHasType(EFFECT_TYPE_ACTIVATE) and re:IsSpellEffect() and rc:IsRelateToEffect(re)
		and Duel.GetLocCount(tp,"M")>0 and rc:IsCanBeSpecialSummoned(e,0,tp,true,false,POS_FACEUP_DEFENSE)
end
function s.oop11(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	local rc=re:GetHandler()
	rc:CancelToGrave()
	rc:AddMonsterAttribute(TYPE_EFFECT)
	Duel.SpecialSummonStep(rc,0,tp,tp,true,false,POS_FACEUP_DEFENSE)
	local e1=MakeEff(c,"FC","M")
	e1:SetCode(EVENT_CHAINING)
	e1:SetProperty(EFFECT_FLAG_CANNOT_DISABLE)
	e1:SetReset(RESET_EVENT+RESETS_STANDARD)
	e1:SetOperation(aux.chainreg)
	rc:RegisterEffect(e1)
	local e2=MakeEff(c,"FC","M")
	e2:SetCode(EVENT_CHAIN_SOLVED)
	e2:SetReset(RESET_EVENT+RESETS_STANDARD)
	e2:SetOperation(s.ooop112)
	rc:RegisterEffect(e2)
	local e3=MakeEff(c,"I","M")
	e3:SetCategory(CATEGORY_DRAW+CATEGORY_DESTROY)
	e3:SetReset(RESET_EVENT+RESETS_STANDARD)
	e3:SetCost(s.oocost113)
	e3:SetTarget(s.ootar113)
	e3:SetOperation(s.ooop113)
	rc:RegisterEffect(e3)
	local e4=MakeEff(c,"S")
	e4:SetCode(EFFECT_COUNTER_PERMIT|COUNTER_SPELL)
	e4:SetReset(RESET_EVENT+RESETS_STANDARD-RESET_TURN_SET-RESET_TEMP_REMOVE)
	e4:SetValue(LSTN("M"))
	rc:RegisterEffect(e4)
	local e5=MakeEff(c,"S")
	e5:SetCode(EFFECT_COUNTER_LIMIT|COUNTER_SPELL)
	e5:SetReset(RESET_EVENT+RESETS_STANDARD-RESET_TURN_SET-RESET_TEMP_REMOVE)
	e5:SetValue(3)
	rc:RegisterEffect(e5)
	local e6=MakeEff(c,"S")
	e6:SetCode(EFFECT_CHANGE_LEVEL_FINAL)
	e6:SetProperty(EFFECT_FLAG_CANNOT_DISABLE)
	e6:SetReset(RESET_EVENT+RESETS_STANDARD-RESET_TURN_SET-RESET_TEMP_REMOVE)
	e6:SetValue(4)
	rc:RegisterEffect(e6)
	local e7=MakeEff(c,"S")
	e7:SetCode(EFFECT_SET_BASE_ATTACK)
	e7:SetProperty(EFFECT_FLAG_CANNOT_DISABLE)
	e7:SetReset(RESET_EVENT+RESETS_STANDARD-RESET_TURN_SET-RESET_TEMP_REMOVE)
	e7:SetValue(0)
	rc:RegisterEffect(e7)
	local e8=MakeEff(c,"S")
	e8:SetCode(EFFECT_SET_BASE_DEFENSE)
	e8:SetProperty(EFFECT_FLAG_CANNOT_DISABLE)
	e8:SetReset(RESET_EVENT+RESETS_STANDARD-RESET_TURN_SET-RESET_TEMP_REMOVE)
	e8:SetValue(2000)
	rc:RegisterEffect(e8)
	local e9=MakeEff(c,"S")
	e9:SetCode(EFFECT_CHANGE_ATTRIBUTE)
	e9:SetProperty(EFFECT_FLAG_CANNOT_DISABLE)
	e9:SetReset(RESET_EVENT+RESETS_STANDARD-RESET_TURN_SET-RESET_TEMP_REMOVE)
	e9:SetValue(ATTRIBUTE_WATER)
	rc:RegisterEffect(e9)
	local e10=MakeEff(c,"S")
	e10:SetCode(EFFECT_CHANGE_RACE)
	e10:SetProperty(EFFECT_FLAG_CANNOT_DISABLE)
	e10:SetReset(RESET_EVENT+RESETS_STANDARD-RESET_TURN_SET-RESET_TEMP_REMOVE)
	e10:SetValue(RACE_SPELLCASTER)
	rc:RegisterEffect(e10)
	Duel.SpecialSummonComplete()
end
function s.ooop112(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	if re:IsHasType(EFFECT_TYPE_ACTIVATE) and re:IsSpellEffect() and c:GetFlagEffect(1)>0 then
		c:AddCounter(COUNTER_SPELL,1)
	end
end
function s.oocost113(e,tp,eg,ep,ev,re,r,rp,chk)
	local c=e:GetHandler()
	if chk==0 then
		return c:IsCanRemoveCounter(tp,COUNTER_SPELL,3,REASON_COST)
	end
	c:RemoveCounter(tp,COUNTER_SPELL,3,REASON_COST)
end
function s.ootar113(e,tp,eg,ep,ev,re,r,rp,chk)
	local c=e:GetHandler()
	if chk==0 then
		return Duel.IsPlayerCanDraw(tp,1)
	end
	Duel.SOI(0,CATEGORY_DESTROY,c,1,0,0)
	Duel.SOI(0,CATEGORY_DRAW,nil,0,tp,1)
end
function s.ooop113(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	if c:IsRelateToEffect(e) and Duel.Destroy(c,REASON_EFFECT)>0 then
		Duel.Draw(tp,1,REASON_EFFECT)
	end
end